usr/sbin/pbuilder
usr/share/pbuilder/pbuilderrc
usr/lib/pbuilder/pbuilder-apt-config
usr/lib/pbuilder/pbuilder-buildpackage*
usr/lib/pbuilder/pbuilder-checkparams
usr/lib/pbuilder/pbuilder-createbuildenv
usr/lib/pbuilder/pbuilder-loadconfig
usr/lib/pbuilder/pbuilder-modules
usr/lib/pbuilder/pbuilder-runhooks
usr/lib/pbuilder/pbuilder-satisfydepends*
usr/lib/pbuilder/pbuilder-unshare-wrapper
usr/lib/pbuilder/pbuilder-updatebuildenv

usr/bin/pdebuild
usr/lib/pbuilder/pdebuild-checkparams
usr/lib/pbuilder/pdebuild-internal

/usr/bin/debuild-pbuilder
/etc/pbuilder/buildd-config.sh
/usr/share/bash-completion/completions/pbuilder

usr/share/doc
